#!/usr/bin/env node
'use strict';

var program = require('commander');

program
  .version('0.1.0')
  .option('-f, --file [file]', 'xml file path')
  .parse(process.argv);

var struct = require('./lib/struct');
var load = require('./lib/load');

load(program.file, function(err, result) {
  if (err) {
    return console.error(err);
  }
  struct.analyse(result);
  console.log(struct.generate());
});
